--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/KingOfTurkey38/MineReset38
build-by-default: true
branches:
- main
projects:
  MineReset38:
    path: ""
    libs:
      - src: sof3/await-generator/await-generator
        version: ^3.1.0
      - src: sof3/await-std/await-std
        version: ^0.2.0
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
        branch: PM4
...
